[package]
edition = "2024"
name = "gopherbadge-rs"
version = "0.1.0"
license = "MIT"
authors = ["flejz"]

[dependencies]
accelerometer = "0.12.0"
cortex-m = "0.7"
cortex-m-rt = "0.7"
cortex-m-semihosting = "0.5.0"
defmt = "1"
defmt-rtt = "1"
display-interface-spi = "0.5.0"
embedded-graphics = "0.8"
embedded-hal = "1.0.0"
embedded-hal-bus = "0.3.0"
embedded-hal-compat = "0.13.0"
embedded-time = "0.12"
heapless = "0.8.0"
lis3dh = "0.4.3"
mipidsi = "0.9.0"
panic-probe = { version = "1", features = ["print-defmt"] }
rp2040-boot2 = "0.3"
rp2040-hal = { version = "0.11.0", features = ["rt", "critical-section-impl"] }
smart-leds = "0.4.0"
tinybmp = "0.6.0"
usb-device = "0.3"
usbd-serial = "0.2.2"
ws2812-pio = "0.9.0"

# cargo build/run
[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

# cargo build/run --release
[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

# # cargo test
# [profile.test]
# codegen-units = 1
# debug = 2
# debug-assertions = true
# incremental = false
# opt-level = 3
# overflow-checks = true

# # cargo test --release
# [profile.bench]
# codegen-units = 1
# debug = 2
# debug-assertions = false
# incremental = false
# lto = 'fat'
# opt-level = 3
